<?php
echo '<html>';
echo '<head>';
echo '<title>Biodata </title>';
echo '</head>';
echo '<body>';
echo '<table border="1">';
echo '<tr>';
echo '<td> Name</td>';
echo '<td>LEOW SHENG WEI </td>';
echo '<td><img src="https://author.uthm.edu.my/studentstaffimages/AI190232.jpg" width="250" height="200"> </td>';
echo '</tr>';
echo '<tr>';
echo '<td> Date of birth</td>';
echo '<td colspan="2"> 13 July 1999</td>';
echo '</tr>';
echo '<tr>';
echo '<td> Religion</td>';
echo '<td colspan="2"> Buddha</td>';
echo '</tr>';
echo '<tr>';
echo '<td> Race</td>';
echo '<td colspan="2">Chinese</td>';
echo '</tr>';
echo '<tr>';
echo '<td rowspan="4"> Address</td>';
echo '<td >Street</td>';
echo '<td >No 24,Jalan Sutera 10,Taman Sutera</td>';
echo '<tr>';
echo '<td>Town</td>';
echo '<td>Kampung Jawa</td>';
echo '</tr>';
echo '<tr>';
echo '<td>District</td>';
echo '<td>Segamat</td>';
echo '</tr>';
echo '<tr>';
echo '<td>State</td>';
echo '<td>Johor</td>';
echo '</tr>';
echo '</tr>';
echo '<tr>';
echo '<td rowspan="3"> Contact</td>';
echo '<td >Mobile Phone</td>';
echo '<td >013-7929984</td>';
echo '<tr>';
echo '<td>Social Media</td>';
echo '<td>Facebook</td>';
echo '</tr>';
echo '<tr>';
echo '<td>Website</td>';
echo '<td><a href="C:\Users\User\Desktop\biodata.html">My Website<a></td>';
echo '</tr>';
echo '</tr>';
echo '<tr>';
echo '<td>Course and Institution</td>';
echo '<td colspan="2">BIC 21203 WEB DEVELOPMENT</td>';
echo '</tr>';
echo '<tr>';
echo '<td>Programming Skill</td>';
echo '<td colspan="2">C, C# , Java</td>';
echo '</tr>';
echo '<tr>';
echo '<td>Personal Interest</td>';
echo '<td colspan="2">Playing game and badminton sports</td>';
echo '</tr>';
echo '<tr>';
echo '<td>Plan in 2022</td>';
echo '<td colspan="2">Hope the Pandemic Covid-19 can be solve and <br>';
echo 'can back to the campus as soon</td>';
echo '</tr>';
echo '</table>';
echo '';
echo '</table>';
echo '</body>';
echo '</html>';
?>