<?php

echo '<html>';
echo '<head>';
echo '</head>';
echo '<body>';
echo '<img src="https://www.utusan.com.my/wp-content/uploads/WhatsApp-Image-2020-11-30-at-5.05.44-PM.jpeg" width="240" height="200">';
echo '<span style="color:#ff0000"><h1>BIC21203 WEB DEVELOPMENT </h1></span>';
echo '<span style="color:#ff0000"><h1>Session 5</h1></span>';
echo '<br><br>';
echo '<h2> Name: LEOW SHENG WEI';
echo '<br>';
echo 'Metric Num:AI190232';
echo '<br>';
echo 'Lab Activities:';
echo '<br><br>';
echo '<table border="1">';
echo '<tr>';
echo '<td><b>LAB NO</b></td>';
echo '<td><b>TITLE</b></td>';
echo '<td><b>LESSONS LEARNED</b></td>';
echo '</tr>';
echo '<tr>';
echo '<td>2</td>';
echo '<td><a href="http://pelantar.xyz/BIC21203/AI190232/L2/biodata.html">My Biodata (HTML)</a><br><a href="http://pelantar.xyz/BIC21203/AI190232/L2/house.html">My Dream House (HTML)</a></td>';
echo '<td>The lesson learned in this task was I do the initial revision about all the tags that I already learned before this course such as table , hyperlink, image ,background , font color , background and others. I also learn to design the wireframe of the web page before I start the web page development to make sure the process will be smooth and success. Besides the skill and knowledge learn from this task , some difficulties also faced when I created the table. The nested table and column space caused the table was not tidy increase my knowledge about the column space and row space after I searching information from internet to solve the problem. The different between the photo in the computer and image from the internet also teaching me need use different url to make sure the image can be display well. If wrong use the url , the image will be only a small graphic icon display on the web page . The email hyperlink where need used the format mailto also very important criteria to differentiate normal hyperlink and email. In conclusion ,  I already do all the revision about the html page code that I learnt before and get some sub knowledge that maybe not learnt in course but more in practical. The different exercise done by self can improve the skill that may not learn in course and become more knowledgeable and professional web developer.</td>';
echo '</tr>';
echo '<tr>';
echo '<td>3</td>';
echo '<td><a href="http://pelantar.xyz/BIC21203/AI190232/L3/Home.html">Product Catalog (HTML & CSS)</a></td>';
echo '<td>The lesson I learned in this lab was using the CSS in the html to make the web page become more colorful and more pattern to attract users to used your web page. I learn more about the color codes, navigation and side bar that using the width concept of the web page. The used of the form elements such as label and the button to make some interaction between user and web page can increase the usability of the web page. The difficulties may face by me was some design problem which was the table size or picture width and height which all these problems were easily to settle but needed to take more time where to make sure the consistency of the web page. The finding of the image also take a lot of time to make sure all pictures were  clear to see and suitable. All this lesson will help me improve the design of the web page and can provide more human computer interface elements in my web page in the future.</td>';
echo '<tr>';
echo '<td>4</td>';
echo '<td><a href="http://pelantar.xyz/BIC21203/AI190232/L3/Home.html">Simple Website(HTML & CSS & JavaScript</a></td>';
echo '<td>The lesson that I learned in this lab was using the javascript to do some function in html to make the web page can validate the text field, pass value to next page and some easy calculation of total price and discount. I learn about using the conditional statement in the javascript which is if and else statement to make the calculation can execute to get correct answer. Some difficulties that face by my was the display passing value from previous page where to get the id name of the variable previous page was so hard then I create a new id for hold the value for successful display the result. This lesson will help me to avoid the value of another page to disappear and can display all the result successful.';
echo '</td>';
echo '</tr>';
echo '</table>';
echo '</body>';
echo '</html>';
?>
